baseURL = "https://sharminmou.github.io/portfolio-saraban-salsabila/"
languageCode = "en"
title = "Saraban Salsabila"
theme = "hugo-initio"

[params]
name = "Saraban Salsabila"
description = "Research Enthusiast"
email = "sarabansalsabila@iut-dhaka.edu"
phone = "+8801763711909"
address = "Nikunja-2, Khilkhet-1229, Dhaka"
year = 2024
avatar = "images/sara.jpeg"
avatarclass = "circle"
background = ""
banner = "images/bg_head_sara.jpeg"
favicon = "images/gt_favicon.png"
DateForm = ""
author = "Sergey Pozhilov (GetTemplate.com)"

showSubheader = true
showServices = true
showRecentWorks = true
showExtraCurricular = true
showDownloads = true
showClients = false

showFooterContact = true
showFooterFollowMe = true
showFooterTextWidget = false
showFooterFormWidget = false

[[menu.main]]
name = "home"
url = "/"
weight = 1
[[menu.main]]
name = "about"
url = "/about/"
weight = 2
[[menu.main]]
name = "experience"
url = "/post/"
weight = 3
[[menu.main]]
name = "research"
url = "/research/"
weight = 4

[params.disqus]
site = "hugo-initio-site.disqus.com"

[params.sharethis]
property = "123456789012345678901234"
custom = true

[params.google.analytics]
trackerID = "GA-000000000-0"

[[params.social]]
title = "email"
url = "mailto:sarabansalsabila@iut-dhaka.edu"
icon = "fas fa-envelope-square"
footer = true
sharethis = true
network = "email"
[[params.social]]
title = "facebook"
url = "https://www.facebook.com/ssabila19?mibextid=ZbWKwL"
icon = "fab fa-facebook-square"
footer = true
sharethis = true
network = "facebook"
[[params.social]]
title = "twitter"
url = "https://twitter.com/nickname"
icon = "fab fa-twitter-square"
footer = false
sharethis = true
network = "twitter"
[[params.social]]
title = "instagram"
url = "https://www.instagram.com/nickname"
icon = "fab fa-instagram"
footer = false
sharethis = false
network = ""
[[params.social]]
title = "google+"
url = "https://plus.google.com/+nickname"
icon = "fab fa-google-plus-square"
footer = false
sharethis = true
network = "googleplus"
[[params.social]]
title = "linkedin"
url = "https://www.linkedin.com/in/saraban-salsabila"
icon = "fab fa-linkedin"
footer = false
sharethis = true
network = "linkedin"
[[params.social]]
title = "tumblr"
url = "https://nickname.tumblr.com"
icon = "fab fa-tumblr-square"
footer = false
sharethis = false
network = "tumblr"
[[params.social]]
title = "github"
url = "https://github.com/nickname"
icon = "fab fa-github"
footer = false
sharethis = false
network = ""
[[params.social]]
title = "WhatsApp"
url = "https://wa.me/qr/AXRRWLFZRSJAE1"
icon = "fab fa-whatsapp"
footer = true
sharethis = true
network = "whatsapp"

[[params.social]]
title = "Telegram"
url = "t.me/Sarabansa"
icon = "fab fa-telegram-plane"
footer = true
sharethis = true
network = "telegram"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true